[package]
name = "day_01"
version = "0.1.0"
authors = ["Den4200 <dennis@dennispham.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "solution"
path = "solution.rs"

[dependencies]
itertools = "0.10.0"
